name: fetch upstream
permissions: {}

on:
  push:
    branches:
      - "master"
  schedule:
    - cron: "0 */10 * * *"
  workflow_dispatch:

env:
  PATCH_REF: "patched"

jobs:
  git:
    if: ${{ github.event.pusher.username != 'github-actions[bot]' }}
    name: git
    permissions:
      contents: write
    runs-on: ubuntu-slim
    steps:
      - uses: actions/cache/restore@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: src/*/.git/
          key: cached-source-codes
          restore-keys: |
            cached-source-codes
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 100
          path: src/mise
          persist-credentials: true
          ref: master
          token: "${{ secrets.UPDATE_WORKFLOW_TOKEN }}"
      - name: update
        env:
          PATCH_REF: ${{ env.PATCH_REF }}
        id: update
        shell: bash
        run: |
          set -euxo pipefail
          cd ./src/mise/
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote remove upstream || true
          git remote add upstream https://github.com/jdx/mise.git
          git fetch upstream --depth 100 --prune

          if ! git pull --rebase upstream main; then
              git rebase --abort
              git checkout -B main upstream/main
              git rm -rf .github/
              git add -A && git commit -m 'cleanhouse: reduce the chance of rebase conflict'
              git checkout -B master origin/master
              git rebase main
          fi

          git push -f origin "HEAD:master"
          git push -f origin "HEAD:${PATCH_REF}"
          git reflog expire --expire-unreachable=all \
              && git gc --aggressive --prune --no-quiet
      - uses: actions/cache/save@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: src/*/.git/
          key: cached-source-codes
